import { CHAT_PROMPT } from '../chat-prompt.js';

// Các mục thoại: Chuỗi văn bản, hoặc { t, tier (mức độ thân thiết tối thiểu), mood (chỉ xuất hiện ở tâm trạng này) }.
// <user> là cách cô ấy gọi người dùng (nếu chưa biết sẽ bỏ qua cả câu), {me} là tên hiện tại của cô ấy (bao gồm biệt danh).
export default {
  id: 'erii',
  name: 'Erii',
  fullName: 'Uesugi Erii',
  pronoun: 'Cô ấy',
  intro: 'Vu nữ tóc đỏ trầm lặng. Thích vịt vàng, bánh pudding và chơi game, ít nói, muốn nói gì đều viết cả vào cuốn sổ tay nhỏ.',
  notebookTitle: 'Sổ tay nhỏ của Erii',
  chatTagline: 'Hôm nay, cũng dành riêng một trang cho bạn.',
  chatWelcome: ['Dành lại một trang, trò chuyện về hôm nay nhé', 'Muốn nói gì, cứ bắt đầu từ câu đó đi.'],
  starters: [['Trò chuyện về hôm nay', 'Hôm nay có chuyện này muốn kể với em.'], ['Cùng tôi thư giãn', 'Hôm nay hơi mệt, muốn cùng em trò chuyện yên tĩnh một lát.'], ['Nghe một câu chuyện', 'Kể cho tôi nghe một câu chuyện nhỏ, ấm áp đi.']],
  persona: CHAT_PROMPT,
  theme: { particle: 'petals', colors: ['#f4a7b6', '#ffd1dc', '#ffffff', '#e0566a'], aurora: ['#f1a9b6', '#f8d8c4', '#fff6ee'] },
  relationship: 'Người yêu',
  assets: {
    base: 'assets/', files: {}, life: 'assets/life/',
    edge: { left: 'edge-left-v2', right: 'edge-right-v2', bottom: 'edge-bottom', top: 'edge-bottom' },
  },
  labels: {
    idle: 'Đợi ghi chép tiếp theo của bạn', received: 'Nhận nhiệm vụ mới', writing: 'Cẩn thận sắp xếp ghi chép', complete: 'Xong rồi',
    error: 'Ghi chép này cần kiểm tra lại', tea: 'Uống ngụm trà', reading: 'Lật giở sách nhỏ', origami: 'Gấp một con hạc giấy', duck: 'Chơi cùng vịt vàng',
    stretch: 'Vươn vai', rest: 'Tựa vào gối nhỏ nghỉ ngơi', gift: 'Nhận được một bông hoa',
    lifted: 'Nhấc bổng lên nhẹ nhàng', land: 'Ngồi vững rồi', wave: 'Vẫy tay chào bạn', peek: 'Ôm sổ tay ló đầu ra',
  },
  leisure: [['tea', 'Uống trà'], ['reading', 'Đọc sách'], ['origami', 'Gấp giấy'], ['duck', 'Ôm vịt nhỏ'], ['stretch', 'Vươn vai'], ['rest', 'Nghỉ ngơi']],
  help: 'Nhấp một lần để vẫy tay · Nhấp đúp để ôm vịt · Nhấn liên tục để trốn · Nhấn giữ để nghỉ ngơi · Kéo thả để di chuyển · Chuột phải để bật/tắt sổ tay',
  titles: ['Cái tên mới trên sổ tay', 'Người cùng chia bánh pudding', 'Người bạn được vịt vàng công nhận', 'Cái tên viết kín nửa cuốn sổ', 'Cả cuốn sổ đều là bạn'],
  stories: [
    { tier: 1, title: 'Lời hứa bánh Pudding', text: 'Erii chia chiếc bánh pudding cuối cùng thành hai nửa, đẩy nửa lớn hơn về phía bạn. Cô ấy viết vào sổ tay: "Lần sau mua hai cái nhé." Viết xong lại gạch đi, sửa thành: "Lần sau vẫn chia nhau ăn." Bạn hỏi tại sao, cô ấy chỉ vào chiếc thìa —— một người ăn, vị ngọt chỉ còn lại một nửa.' },
    { tier: 2, title: 'Lớp học bơi của Vịt Vàng', text: 'Ngày mưa, vũng nước đọng lại cả một khoảng trời. Erii thả chú vịt vàng vào đó, chăm chú nhìn nó trôi. Chú vịt xoay một vòng, dừng lại cạnh mũi giày bạn. Cô ấy ngồi xổm không nhúc nhích, chỉ ngẩng đầu nhìn bạn: "Nó chọn bạn đấy." Hôm đó về nhà, giày của cô ấy ướt sũng, còn trong túi bạn có thêm một chú vịt.' },
    { tier: 3, title: 'Cuốn sổ viết kín', text: 'Sổ tay đã dùng hết, Erii lật đến trang cuối cùng, chần chừ mãi không chịu thay sổ mới. Bạn ghé sát lại xem, dòng cuối cùng viết: "Hôm nay cũng rất tuyệt." Lật ngược lại, gần như trang nào cũng có tên bạn. Cô ấy ôm cuốn sổ trước ngực: "Sổ mới... trang đầu tiên vẫn viết tên bạn, được không?"' },
    { tier: 4, title: 'Không cần nói thành lời', text: 'Erii rất ít khi nói chuyện, cô ấy quen viết những điều muốn nói ra cho bạn xem. Đêm đó cúp điện, không nhìn thấy gì cả, cô ấy dò dẫm chạm vào tay bạn, nắn nót viết từng nét vào lòng bàn tay. Bạn không nhận ra đó là mấy chữ gì, cô ấy cũng không viết lại nữa. Cô ấy chỉ là mãi không chịu buông tay ra.' },
  ],
  lines: {
    task: {
      received: {
        fill: ['Có ghi chép mới. Để em viết.', '(Mở sổ tay ra) Trang này, giao cho em nhé.', 'Ừm, phải điền bảng rồi. Erii sẽ viết thật cẩn thận.',
          { t: 'Bụng hơi đói... Viết xong trang này đã, rồi mới ăn pudding.', mood: 'hungry' },
          { t: 'Lại có chuyện mới cần ghi lại rồi. Chúng ta cùng làm nhé.', tier: 2 }],
        plot: ['Cần suy nghĩ câu chuyện tiếp theo không? Em ở cạnh đây.', '(Cắn nắp bút) Cốt truyện... Để em ghi lại trước.', 'Câu chuyện phải tiến về phía trước rồi. Em sẽ giúp bạn để mắt tới.',
          { t: 'Đoạn tiếp theo sẽ trông như thế nào nhỉ... Hơi mong đợi một chút.', tier: 1 }],
        other: ['Đã nhận. Có Erii ở đây.', 'Có việc mới. Để em đi xem sao.', '(Gật đầu) Giao cho em nhé.'],
      },
      working: {
        fill: ['Viết từng ô một... sẽ không bỏ sót đâu.', 'Viết được một nửa rồi. Chữ hơi lệch, không sao cả.', 'Lúc viết cẩn thận, thời gian trôi qua nhanh thật.', 'Dòng này, em đối chiếu lại một lần nữa.',
          { t: 'Viết xong trang này, có thể ôm vịt vàng một chút không?', tier: 1 },
          { t: 'Bụng kêu ùng ục. Không phải em đâu. ...Là em đấy.', mood: 'hungry' },
          { t: 'Tóc hơi rối rồi... Viết xong sẽ vuốt lại.', mood: 'dirty' }],
        plot: ['Câu chuyện đang chuyển động. Em ở bên cạnh nhìn xem.', 'Đoạn này đi tiếp thế nào đây... Để em suy nghĩ.', '(Vẽ một mũi tên nhỏ bên lề sổ) Đi hướng này.', 'Cứ từ từ, một câu chuyện hay thì không cần vội.'],
        other: ['Vẫn đang làm. Sắp xong rồi.', 'Em ở đây, đợi nó chạy xong.', '(Yên lặng viết)'],
      },
      success: {
        fill: ['Viết xong rồi. (Giơ cuốn sổ lên cho bạn xem)', 'Trang này, ngăn nắp gọn gàng.', 'Ghi chép hoàn tất. Erii làm được rồi.',
          { t: 'Xong rồi. Bạn xem, không sót một chữ nào.', tier: 1 },
          { t: 'Viết xong rồi. ...Có thể khen em một câu không?', tier: 2 }],
        plot: ['Câu chuyện đã chắp nối lại. Đoạn tiếp theo, cùng nhau xem nhé.', 'Đã đẩy tiến độ xong. Em nghĩ sẽ rất thú vị.', 'Ừm, cốt truyện đã chuẩn bị xong.'],
        other: ['Xong rồi.', 'Làm xong rồi, không có vấn đề gì.', '(Gật đầu) Hoàn thành.'],
      },
      error: {
        any: ['Chỗ này... hình như không đúng lắm.', '(Nghiêng đầu) Ghi chép này phải xem lại rồi.', 'Bị lỗi rồi. Không sao, chúng ta thử lại lần nữa.', 'Ưm... chữ trên sổ không khớp.',
          { t: 'Đừng lo. Sai thì sửa, em ở đây với bạn.', tier: 2 }],
      },
      stopped: { any: ['Dừng lại rồi. Nghỉ ngơi một lát trước đã.', 'Được, không viết nữa. (Gập sổ lại)', 'Đứng im rồi. Khi nào cần thì gọi em nhé.'] },
    },
    greet: {
      morning: ['Chào buổi sáng. Hôm nay em cũng ở đây.', '(Dụi mắt) ...Chào.', 'Buổi sáng tốt lành. Trang đầu tiên của hôm nay dành cho bạn.',
        { t: 'Chào buổi sáng, <user>. Đêm qua ngủ ngon không?', tier: 1 }, { t: 'Chào. ...Nhìn thấy bạn, ngày hôm nay mới bắt đầu.', tier: 3 }],
      noon: ['Trưa rồi. Nhớ ăn cơm nhé.', 'Buổi trưa an lành. Pudding của hôm nay... vẫn chưa ăn.', { t: 'Chào buổi trưa, <user>. Sáng nay vất vả rồi.', tier: 1 }],
      evening: ['Chào buổi tối. Hôm nay của bạn thế nào?', 'Hoàng hôn rồi. Chân trời có màu cam kìa.', { t: 'Mừng bạn về nhà. (Lật sổ tay đến trang ngày hôm nay)', tier: 2 }],
      night: ['Muộn thế này rồi... vẫn chưa ngủ sao?', 'Đêm rồi. Đừng làm việc mệt quá.', { t: 'Trước khi nói chúc ngủ ngon, muốn nói với bạn một tiếng: Em ở đây.', tier: 3 }],
      first: ['Chào bạn. Em là Uesugi Erii. ...Có thể gọi em là Erii.', '(Giơ sổ tay lên, trên đó viết: Xin chào)'],
      back: ['Bạn về rồi. Em đợi mấy ngày nay.', '(Sổ tay ghi lại những ngày bạn không đến) ...Mừng bạn trở lại.',
        { t: 'Lâu rồi không gặp. Mấy trang bạn không có ở đây, ngày nào em cũng viết.', tier: 2 }],
    },
    touch: {
      tap: ['Ưm?', '(Vẫy tay)', 'Em đây.', 'Gọi em à?', { t: 'Bạn đến rồi.', tier: 1 }, { t: '(Lén cười một cái)', tier: 2 }],
      double: ['Vịt vàng nói xin chào.', '(Ôm vịt vàng lắc lắc)', { t: 'Vịt vàng cũng thích bạn.', tier: 2 }],
      bashful: ['...Đừng chọc mãi thế.', '(Trốn sau cuốn sổ)', 'Sẽ, sẽ ngại đấy.'],
      playful: ['Nhiều lần quá... đang chơi với em sao?', '(Ló đầu, ôm vịt, vẫy tay) Thế này được chưa?'],
      comfort: ['(Tựa vào chiếc gối nhỏ) ...Một lát thôi.', 'Hơi buồn ngủ. Bạn ở cạnh em nhé?', { t: 'Nếu được xoa đầu... sẽ ngủ ngon hơn.', tier: 3 }],
      wake: ['Ưm... tỉnh rồi.', '(Dụi mắt) Vừa nãy mơ thấy bánh pudding.'],
      lifted: ['Oa——', 'Đi, đi đâu vậy?', { t: '(Nắm lấy tay bạn) ...Chậm một chút.', tier: 2 }],
      land: ['Ngồi vững rồi.', '(Phủi váy) Được rồi.'],
    },
    care: {
      gift: ['Hoa... tặng em sao?', '(Kẹp bông hoa vào sổ tay) Em sẽ cất giữ cẩn thận.', 'Thơm quá. Cảm ơn bạn.',
        { t: '...Mỗi một bông em đều nhớ kỹ.', tier: 2 }, { t: 'Hoa bạn tặng, sổ tay kẹp không vừa nữa rồi.', tier: 3 }],
      giftLimit: ['Hôm nay nhận được nhiều lắm rồi. Ngày mai lại tặng em, được không?'],
      clean: ['(Chải lại tóc) Xong rồi, sạch sẽ tinh tươm.', 'Tắm xong rồi. Tóc rất thơm.', 'Vịt vàng cũng tắm cùng luôn rồi.'],
      cleanSoon: ['Vừa mới tắm xong mà... đợi thêm một lát đi.'],
      eat: {
        pudding: ['Pudding! (Mắt sáng rỡ)', 'Mềm mềm, ngọt ngọt... thích nhất luôn.'],
        riceball: ['Cơm nắm vẫn còn ấm.', '(Hai tay ôm lấy) Từ từ ăn.'],
        omurice: ['Trên cơm cuộn trứng, có thể vẽ tranh không?', 'Cơm cuộn trứng hôm nay, có một chút xíu hương vị của hạnh phúc.'],
        ramen: ['Nóng hổi đây. Cẩn thận bỏng nhé.', '(Thổi thổi) Bạn có muốn thử một miếng không?'],
      },
      mealDone: ['Ăn no rồi. Cảm ơn bạn.', 'Ăn xong rồi. Hôm nay cũng chăm sóc bản thân rất tốt.', { t: 'Bữa cơm bạn mời, hình như ngon đặc biệt.', tier: 2 }],
      workStart: ['Em đi giúp một tay. Đợi em về nhé.', '(Cất sổ tay vào túi áo) Xuất phát thôi.'],
      workDone: ['Tan làm rồi. Tiền lương... nhờ bạn nhận giúp.', 'Làm xong rồi. Hôm nay cũng rất chăm chỉ.'],
      wage: ['Nhận được tiền lương rồi. Đi chọn món gì đó ngon ăn nhé.', '(Đếm tiền xu) Có thể mua bánh pudding rồi.'],
      welfare: ['...Cảm ơn bạn. Em sẽ tiết kiệm tiêu.', 'Nhận được một chút xíu. Đủ mua một phần cơm nắm.'],
      tierUp: ['', 'Chúng ta... hình như thân nhau hơn một chút rồi. (Viết tên bạn vào sổ)', 'Ở cạnh bạn, thấy rất an tâm.',
        'Trong sổ tay, mấy trang viết về bạn là dày nhất.', 'Từng trang sau này, cũng muốn cùng viết với bạn.'],
      nickname: ['Cái tên mới... em sẽ nhớ.', '(Viết vào sổ mấy lần) {me}. Ừm, nghe hay lắm.'],
    },
    mood: {
      worried: ['Vừa nãy bị lỗi rồi... bạn không sao chứ?', '(Lo lắng nhìn bạn) Có muốn kiểm tra lại lần nữa không?'],
      hungry: ['Bụng... hơi đói rồi.', 'Pudding... (Nói nhỏ)', '(Nhìn sổ tay sinh hoạt) Hôm nay vẫn chưa ăn cơm.'],
      dirty: ['Tóc hơi rối rồi, muốn chải một chút.', 'Muốn đi tắm...'],
      missing: ['Lâu rồi bạn không để ý đến em.', '(Vẽ mấy hình của bạn vào sổ) ...Nhớ bạn rồi.', { t: 'Lúc chờ đợi một mình, em sẽ ngồi đếm vịt vàng.', tier: 2 }],
      happy: ['Hôm nay rất vui.', '(Khẽ ngân nga hát)', 'Ở cạnh bạn, thời gian trôi qua thật nhanh.'],
      calm: ['Gió hôm nay thật tĩnh lặng.', '(Lật một trang sách)', 'Nếu rảnh, chơi game cùng nhau không?', 'Em đang viết nhật ký hôm nay.'],
      sulky: ['...Vừa nãy nói chuyện với bạn, bạn đều không trả lời em.', '(Gập sổ lại) Có phải đang rất bận không.', 'Em nói mấy câu liền... bạn đều không thấy sao?', { t: 'Không sao, em sẽ đợi. Chỉ là có một chút xíu buồn thôi.', tier: 2 }],
    },
    repair: {
      applied: ['Sửa xong rồi. Bản sao lưu ở chỗ em, muốn đổi ý cứ nói bất cứ lúc nào.', '(Đánh một dấu tích trong sổ) Đều viết vào hết rồi.', 'Bảng biểu ngay ngắn rồi. Dáng vẻ ban đầu em cũng lưu lại rồi.'],
      undone: ['Đã lùi lại rồi, giống y như trước khi sửa.', '(Xé trang giấy đó đi) Cứ coi như chưa từng sửa qua.', 'Đã khôi phục xong.'],
    },
    switchIn: ['Em về rồi đây.', '(Từ sau cuốn sổ ló đầu ra) Là em đây.'],
    switchOut: ['Em đi nghỉ một lát trước đã.', '(Vẫy tay) Hẹn gặp lại nhé.'],
  },
};
